---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: jupyterhub
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hub.jupyter.org
        namespace: ${workspaceNamespace}
      version: 4.*
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: jupyterhub
  valuesFrom:
    - kind: ConfigMap
      name: jupyterhub-5.2.1-defaults
  targetNamespace: ${releaseNamespace}
