---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-5.2.1-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    hub:
      baseUrl: /jupyter
      config:
        Authenticator:
          admin_users:
            - admin
          allowed_users:
            - user
        DummyAuthenticator:
          password: nutanix/4u
        JupyterHub:
          authenticator_class: dummy
      networkPolicy:
        egress:
          - ports:
              - port: 6443
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: kommander-stripprefixes@kubernetescrd
        traefik.ingress.kubernetes.io/router.tls: "true"
      ingressClassName: kommander-traefik
      pathType: ImplementationSpecific
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-dashboard
  namespace: ${releaseNamespace}
  labels:
    kommander.d2iq.io/application: jupyterhub
data:
  dashboardLink: /jupyter/
  docsLink: "https://z2jh.jupyter.org/en/stable/"
  name: JupyterHub
  version: 5.2.1
