---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnamicharts
  namespace: ${workspaceNamespace}
spec:
  url: "oci://registry-1.docker.io/bitnamicharts"
  interval: 10m
  timeout: 1m
  type: oci
